const { v4: uuidv4 } = require('uuid');
const { run, all } = require('./db');

/**
 * Default instrument for the AI-disclosure study.
 *
 * Question sets 1-3 are asked after EVERY stimulus block, so they are stored
 * with block_id NULL: they are survey-level templates, not tied to one block.
 * Which stimulus a given answer refers to is recorded on the response row
 * (responses.block_id and responses.block_position), not on the question.
 *
 * `question_set` groups statements that share a page and a scale.
 * `question_number` orders statements within a set.
 */

const LIKERT_7 = {
  scaleMax: 7,
  anchors: ['1 = Strongly disagree', '7 = Strongly agree'],
};

const DEFAULT_QUESTIONS = [
  // --- Set 1: single-answer manipulation check --------------------------
  {
    questionSet: 1,
    questionNumber: 1,
    questionType: 'single_choice',
    questionText:
      'What is the AI disclosure format best described the above advertisement?',
    options: [
      'No Label',
      'Text Label ("This was generated by AI")',
      'AI Attribution ("This was generated using GPT-4 and Dall-E by OpenAI")',
      'A Behind-The-Scenes Video',
    ],
  },

  // --- Set 2: perceived transparency, 7-point Likert grid ----------------
  ...[
    'The advertisement is transparent in its AI information disclosure',
    'The advertisement is candid in delivering information about its AI involvement',
    'The advertisement provides clear information about AI involvement',
    'The advertisement is open in communicating its AI involvement',
    'Overall, the advertisement provides relevant information to ensure transparency of its AI involvement',
  ].map((text, i) => ({
    questionSet: 2,
    questionNumber: i + 1,
    questionType: 'likert',
    questionText: text,
    scaleMax: LIKERT_7.scaleMax,
  })),

  // --- Set 3: attitude toward the ad, 7-point Likert grid ----------------
  ...[
    'I would consider accepting this advertisement',
    'I think this advertisement is good',
    'My attitude toward this advertisement is positive',
  ].map((text, i) => ({
    questionSet: 3,
    questionNumber: i + 1,
    questionType: 'likert',
    questionText: text,
    scaleMax: LIKERT_7.scaleMax,
  })),
];

// Prompts shown above each set during the survey.
const SET_PROMPTS = {
  1: '',
  2: 'To what extent do you agree with the following statements (1 = Strongly disagree, 7 = Strongly agree): After watching the above AI-generated advertisement...',
  3: 'To what extent do you agree with the following statements (1 = Strongly disagree, 7 = Strongly agree): After watching the above AI-generated advertisement...',
};

const DEFAULT_DEMOGRAPHICS = [
  {
    questionNumber: 1,
    questionText: 'What is your age?',
    questionType: 'single_choice',
    options: ['18-24', '25-34', '35-44', '45 and above'],
  },
  {
    questionNumber: 2,
    questionText: 'What is your gender?',
    questionType: 'single_choice',
    options: ['Male', 'Female', 'Prefer not to say'],
  },
  {
    questionNumber: 3,
    questionText: 'What is your education level?',
    questionType: 'single_choice',
    options: [
      "Bachelor's Student",
      "Master's Student",
      'PhD Student',
      'Not applicable',
    ],
  },
];

/**
 * Seed the default instrument for a survey. Idempotent: does nothing if the
 * survey already has questions, so re-running never duplicates or overwrites
 * edits made through the admin UI.
 */
const seedDefaultQuestions = async (surveyId) => {
  const existing = await all('SELECT id FROM questions WHERE survey_id = ?', [surveyId]);

  if (existing.length === 0) {
    for (const q of DEFAULT_QUESTIONS) {
      await run(
        `INSERT INTO questions
           (id, survey_id, block_id, question_set, question_number,
            question_text, question_type, scale_max, options)
         VALUES (?, ?, NULL, ?, ?, ?, ?, ?, ?)`,
        [
          uuidv4(),
          surveyId,
          q.questionSet,
          q.questionNumber,
          q.questionText,
          q.questionType,
          q.scaleMax || null,
          q.options ? JSON.stringify(q.options) : null,
        ]
      );
    }
  }

  const existingDemo = await all(
    'SELECT id FROM demographic_questions WHERE survey_id = ?',
    [surveyId]
  );

  if (existingDemo.length === 0) {
    for (const d of DEFAULT_DEMOGRAPHICS) {
      await run(
        `INSERT INTO demographic_questions
           (id, survey_id, question_number, question_text, question_type, options)
         VALUES (?, ?, ?, ?, ?, ?)`,
        [
          uuidv4(),
          surveyId,
          d.questionNumber,
          d.questionText,
          d.questionType,
          JSON.stringify(d.options),
        ]
      );
    }
  }
};

module.exports = {
  seedDefaultQuestions,
  SET_PROMPTS,
  DEFAULT_QUESTIONS,
  DEFAULT_DEMOGRAPHICS,
};
